import { Provider, Address, Subscription, MembershipPass, LiveOrderTracking, InquirySubmission } from './types';

export const INITIAL_ADDRESSES: Address[] = [
  {
    id: 'addr-1',
    label: 'Home',
    street: 'Flat 402, Green Glen Layout, Bellandur',
    landmark: 'Near Sobha Silicon Oasis',
    city: 'Bengaluru',
    pincode: '560103',
    isDefault: true,
  },
  {
    id: 'addr-2',
    label: 'Hostel / PG',
    street: 'Room 214, BVM Hostel, Mota Bazar',
    landmark: 'Opposite SP University Library',
    city: 'Vallabh Vidyanagar',
    pincode: '388120',
    isDefault: false,
  },
  {
    id: 'addr-3',
    label: 'Office (Tech Park)',
    street: 'Tower 4, Infocity / GIFT City Gateway',
    landmark: 'Near TCS / Infocity Circle',
    city: 'Gandhinagar',
    pincode: '382009',
    isDefault: false,
  },
];

export const MEMBERSHIP_PASSES: MembershipPass[] = [
  {
    id: 'pass-student',
    title: 'Student Campus Meal Card',
    tagline: 'Budget-friendly, daily hygienic homestyle food for college & coaching students',
    badge: 'STUDENT SPECIAL',
    targetAudience: 'Student',
    monthlyPrice: 2199,
    pricePerMeal: 84,
    colorScheme: 'from-blue-600 to-indigo-700',
    perks: [
      'Subsidized ₹84/meal price point',
      'Free Takeaway & Parcel Point pickup',
      'Up to 8 skips/month with validity extension',
      'Weekend Special Sweet / Extra Roti free',
      'Campus delivery directly to Hostel gates',
    ],
    popularCity: 'Kota, Vallabh Vidyanagar, Roorkee, Pune, Pilani',
  },
  {
    id: 'pass-corporate',
    title: 'Tech Park Executive Pass',
    tagline: 'Light, healthy, low-oil meals delivered to your desk or cafeteria',
    badge: 'MOST POPULAR',
    targetAudience: 'Office & Tech',
    monthlyPrice: 3199,
    pricePerMeal: 123,
    colorScheme: 'from-orange-600 to-amber-600',
    perks: [
      'Guaranteed 12:15 PM lunch desk delivery',
      'Zero Delivery Fee across all Tech Parks',
      'Daily changing sabzi & lentil rotation',
      'Stainless steel insulated tiffin boxes',
      'Pause anytime when traveling or WFH',
    ],
    popularCity: 'GIFT City, Infocity, BKC Mumbai, Hinjewadi, Bellandur',
  },
  {
    id: 'pass-gourmet',
    title: '7-Star Royal Gourmet VIP Pass',
    tagline: 'Michelin-grade homestyle dining crafted by master regional chefs',
    badge: '7-STAR LUXURY',
    targetAudience: 'VIP Gourmet',
    monthlyPrice: 4499,
    pricePerMeal: 173,
    colorScheme: 'from-amber-600 via-yellow-600 to-amber-800',
    perks: [
      '7-Star Heritage Thalis & Paneer everyday',
      'Authentic pure A2 cow ghee preparation',
      'Dine-in priority seating at partner canteens',
      'Daily sweet treat (Kheer, Gulab Jamun, Halwa)',
      'VIP Dedicated Account Manager',
    ],
    popularCity: 'Ahmedabad, Jaipur, Mumbai, Bengaluru, Hyderabad',
  },
];

export const INITIAL_PROVIDERS: Provider[] = [
  {
    id: 'prov-1',
    name: 'Maa Ki Rasoi (North Indian & Shahi)',
    tagline: 'Authentic Punjabi & North Indian homestyle food prepared in pure desi ghee',
    ownerName: 'Mrs. Sunita Sharma',
    rating: 4.9,
    starTier: '5_star',
    kitchenCategory: 'home_chef',
    city: 'Bengaluru / Gurugram / Delhi',
    reviewCount: 420,
    fssaiNumber: '21223194000412',
    verified: true,
    status: 'active',
    cuisine: ['North Indian', 'Punjabi', 'Homestyle Thali'],
    dietary: ['pure-veg'],
    servicePincodes: ['560103', '560034', '560102', '122002', '110007', '380015'],
    kitchenAddress: 'Sector 2, HSR Layout (Also serving Cyber City & Navrangpura)',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    coverImage: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=1200&q=80',
    subscriberCount: 112,
    startingPriceMonthly: 3199,
    takeawayAvailable: true,
    hasDineIn: false,
    hasParcelPoint: true,
    isOfficeFavorite: true,
    deliverySlots: {
      lunch: '12:15 PM - 1:30 PM',
      dinner: '7:45 PM - 9:00 PM',
    },
    mealCollections: [
      {
        id: 'col-1-1',
        name: 'Ghar Ki Thali (Standard)',
        tagline: 'Perfect balance of fiber, lentils & rotis',
        description: '4 Fresh Phulkas with ghee, Dal Tadka, Seasonal Sabzi, Jeera Rice, Curd & Salad.',
        dietType: 'pure-veg',
        caloriesAvg: 580,
        image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80',
        weeklyPrice: 899,
        monthlyPrice: 3199,
        itemsIncluded: ['4 Phulkas (Desi Ghee)', 'Yellow Dal Tadka', 'Aloo Gobi / Bhindi', 'Steamed Rice', 'Homestyle Dahi', 'Salad'],
      },
      {
        id: 'col-1-2',
        name: 'Shahi Royal 5-Star Thali',
        tagline: 'Paneer preparation everyday + Royal Sweet',
        description: '4 Butter Phulkas, Paneer Butter Masala / Kadhai Paneer, Dal Makhani, Pulao, Gulab Jamun & Raita.',
        dietType: 'pure-veg',
        caloriesAvg: 720,
        image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=600&q=80',
        weeklyPrice: 1199,
        monthlyPrice: 4299,
        itemsIncluded: ['4 Butter Phulkas', 'Paneer Butter Masala', 'Dal Makhani', 'Peas Pulao', 'Boondi Raita', 'Gulab Jamun'],
      },
    ],
    weeklyMenu: [
      {
        day: 'Monday',
        lunch: { curry: 'Paneer Bhurji Gravy', dal: 'Moong Dal Fry', bread: '4 Phulkas', rice: 'Jeera Rice', sides: 'Papad & Salad' },
        dinner: { curry: 'Aloo Methi', dal: 'Arhar Dal Tadka', bread: '4 Phulkas', rice: 'Steamed Rice', sides: 'Dahi' },
      },
      {
        day: 'Tuesday',
        lunch: { curry: 'Mix Veg Korma', dal: 'Chana Dal', bread: '4 Phulkas', rice: 'Matar Rice', sides: 'Boondi Raita' },
        dinner: { curry: 'Palak Kofta', dal: 'Masoor Dal', bread: '4 Phulkas', rice: 'Steamed Rice', sides: 'Pickle & Salad' },
      },
      {
        day: 'Wednesday',
        lunch: { curry: 'Rajma Masala (Homestyle)', dal: 'Dal Tadka', bread: '4 Phulkas', rice: 'Basmati Rice', sides: 'Sirka Onion Salad' },
        dinner: { curry: 'Dum Aloo', dal: 'Yellow Dal', bread: '4 Phulkas', rice: 'Steamed Rice', sides: 'Mint Chutney' },
      },
      {
        day: 'Thursday',
        lunch: { curry: 'Kadhai Paneer', dal: 'Panchmel Dal', bread: '4 Phulkas', rice: 'Jeera Rice', sides: 'Cucumber Raita' },
        dinner: { curry: 'Bhindi Masala', dal: 'Moong Dal', bread: '4 Phulkas', rice: 'Steamed Rice', sides: 'Fryums' },
      },
      {
        day: 'Friday',
        lunch: { curry: 'Amritsari Chole', dal: 'Dal Fry', bread: '4 Phulkas', rice: 'Pulao Rice', sides: 'Carrot Halwa / Sweet' },
        dinner: { curry: 'Kashmiri Baingan', dal: 'Toor Dal', bread: '4 Phulkas', rice: 'Steamed Rice', sides: 'Dahi' },
      },
      {
        day: 'Saturday',
        lunch: { curry: 'Matar Paneer', dal: 'Dal Makhani', bread: '4 Phulkas', rice: 'Jeera Rice', sides: 'Papad & Gulab Jamun' },
        dinner: { curry: 'Lauki Kofta Curry', dal: 'Yellow Dal', bread: '4 Phulkas', rice: 'Steamed Rice', sides: 'Salad' },
      },
      {
        day: 'Sunday',
        lunch: { curry: 'Special Shahi Paneer Feast', dal: 'Dal Tadka', bread: '4 Butter Naan/Phulkas', rice: 'Veg Biryani Rice', sides: 'Kheer' },
        dinner: { curry: 'Sev Tamatar Ki Sabzi', dal: 'Khichdi / Kadhi Rice', bread: '3 Phulkas', rice: 'Khichdi', sides: 'Papad' },
      },
    ],
  },
  {
    id: 'prov-2',
    name: 'Shreeji Kathiyawadi & Gujarati Mess',
    tagline: 'Desi Baingan Bharta, Bajra Rotla with White Butter, Sev Tameta & Kadhi Khichdi',
    ownerName: 'Shri Jagdishbhai Patel',
    rating: 4.8,
    starTier: '4_star',
    kitchenCategory: 'student_mess',
    city: 'Ahmedabad / Gandhinagar / Rajkot / Surat',
    reviewCount: 380,
    fssaiNumber: '21222187000109',
    verified: true,
    status: 'active',
    cuisine: ['Gujarati', 'Kathiyawadi', 'Traditional Mess'],
    dietary: ['pure-veg', 'jain'],
    servicePincodes: ['380015', '382007', '382009', '382355', '360005', '395007', '390002', '388120'],
    kitchenAddress: 'Infocity Food Court & BVM College Hub, Gujarat',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    coverImage: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=1200&q=80',
    subscriberCount: 165,
    startingPriceMonthly: 2599,
    takeawayAvailable: true,
    hasDineIn: true,
    hasParcelPoint: true,
    isStudentFavorite: true,
    isOfficeFavorite: true,
    deliverySlots: {
      lunch: '11:45 AM - 1:15 PM',
      dinner: '7:00 PM - 8:30 PM',
    },
    mealCollections: [
      {
        id: 'col-2-1',
        name: 'Kathiyawadi Desi Thali (Rotla + Ghee)',
        tagline: 'Ringan Bhartho, 2 Makai/Bajra Rotla, Ghee & Gud, Masala Chaas',
        description: 'Authentic Saurashtra taste with Sev Tameta, Ringna no Olo, Chutney, Chaas & Khichdi.',
        dietType: 'pure-veg',
        caloriesAvg: 620,
        image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
        weeklyPrice: 799,
        monthlyPrice: 2599,
        itemsIncluded: ['Ringan Bhurtha / Sev Tameta', '2 Desi Bajra Rotla (White Butter)', 'Gujarati Kadhi & Vaghareli Khichdi', 'Garlic Chutney & Gud', 'Chilled Chaas'],
      },
      {
        id: 'col-2-2',
        name: 'Student Unlimited Mess Dine-in Pass',
        tagline: 'Unlimited lunch & dinner buffet seating at Infocity & Campus Mess',
        description: 'Phulkas, 2 Sabzis, Dal, Rice, Chaas, Sweet & Farsan. Dine-in or Parcel Takeaway.',
        dietType: 'pure-veg',
        caloriesAvg: 700,
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
        weeklyPrice: 699,
        monthlyPrice: 2399,
        itemsIncluded: ['Unlimited Phulkas', '2 Daily Sabzis', 'Dal-Bhat', 'Farsan / Khaman', 'Chaas Glass', 'Sunday Sweet'],
      },
    ],
    weeklyMenu: [
      {
        day: 'Monday',
        lunch: { curry: 'Sev Tameta Ki Sabzi', dal: 'Gujarati Khatti-Meethi Dal', bread: '4 Phulkas or 2 Rotla', rice: 'Vaghareli Khichdi', sides: 'Garlic Chutney & Chaas' },
        dinner: { curry: 'Bhindi Masala', dal: 'Kadhi', bread: '4 Rotis', rice: 'Steamed Rice', sides: 'Gud & Ghee' },
      },
      {
        day: 'Tuesday',
        lunch: { curry: 'Ringna no Olo (Baingan Bhartha)', dal: 'Mug Dal Moghar', bread: '2 Bajra Rotla', rice: 'Jeera Rice', sides: 'Papad & Masala Chaas' },
        dinner: { curry: 'Dudhi Chana Dal', dal: 'Kadhi', bread: '4 Phulkas', rice: 'Khichdi', sides: 'Salad' },
      },
      {
        day: 'Wednesday',
        lunch: { curry: 'Rajasthani Gatta Curry', dal: 'Toor Dal Fry', bread: '4 Phulkas', rice: 'Matar Pulao', sides: 'Khaman Dhokla & Chaas' },
        dinner: { curry: 'Aloo Rasavala', dal: 'Kadhi', bread: '4 Phulkas', rice: 'Khichdi', sides: 'Pickle' },
      },
      {
        day: 'Thursday',
        lunch: { curry: 'Lasaniya Bataka (Garlic Potato)', dal: 'Tuver Dal', bread: '2 Rotla', rice: 'Rice', sides: 'Chaas & Papad' },
        dinner: { curry: 'Karela Kaju Masala', dal: 'Yellow Dal', bread: '4 Phulkas', rice: 'Steamed Rice', sides: 'Gud' },
      },
      {
        day: 'Friday',
        lunch: { curry: 'Undhiyu & Puri (Special)', dal: 'Gujarati Dal', bread: '5 Puris / Phulkas', rice: 'Pulao', sides: 'Jalebi & Chaas' },
        dinner: { curry: 'Sev Dungri (Onion Sev)', dal: 'Kadhi', bread: '4 Phulkas', rice: 'Khichdi', sides: 'Papad' },
      },
      {
        day: 'Saturday',
        lunch: { curry: 'Dal Baati Churma (Heritage)', dal: 'Panchmel Dal', bread: '3 Ghee Baatis', rice: 'Rice', sides: 'Churma & Garlic Paste' },
        dinner: { curry: 'Sukhi Bhaji', dal: 'Kadhi', bread: '4 Phulkas', rice: 'Khichdi', sides: 'Chaas' },
      },
      {
        day: 'Sunday',
        lunch: { curry: 'Shahi Paneer Gujarati Style', dal: 'Gujarati Kadhi', bread: '4 Soft Phulkas', rice: 'Veg Biryani', sides: 'Basundi / Kheer' },
        dinner: { curry: 'Methi Papad Nu Shaak', dal: 'Mug Dal', bread: '4 Phulkas', rice: 'Khichdi', sides: 'Papad' },
      },
    ],
  },
  {
    id: 'prov-3',
    name: 'Maharaja 7-Star Royal Heritage Feast',
    tagline: 'Luxury royal Indian dining with silver-foil sealed brass thermal carriers',
    ownerName: 'Chef Ranveer Rathore',
    rating: 5.0,
    starTier: '7_star',
    kitchenCategory: 'gourmet_dining',
    city: 'Jaipur / Udaipur / Mumbai / Delhi',
    reviewCount: 290,
    fssaiNumber: '21221190000781',
    verified: true,
    status: 'active',
    cuisine: ['Royal Rajasthani', 'Mughlai', 'Heritage 7-Star'],
    dietary: ['pure-veg'],
    servicePincodes: ['302017', '313001', '400076', '110007', '560103', '380015'],
    kitchenAddress: 'Heritage Kitchen, Civil Lines & Malviya Nagar Hub',
    avatar: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&w=200&q=80',
    coverImage: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=1200&q=80',
    subscriberCount: 84,
    startingPriceMonthly: 4999,
    takeawayAvailable: true,
    hasDineIn: true,
    hasParcelPoint: false,
    isOfficeFavorite: true,
    deliverySlots: {
      lunch: '12:30 PM - 1:45 PM',
      dinner: '8:00 PM - 9:30 PM',
    },
    mealCollections: [
      {
        id: 'col-3-1',
        name: 'Maharaja 7-Star Royal Thali',
        tagline: 'Paneer Makhani, Panchmel Dal, Missi Roti & Dry Fruit Churma',
        description: 'Exquisite 7-Star gourmet preparation with pure saffron, A2 cow ghee, almond kheer, and shahi gravies.',
        dietType: 'pure-veg',
        caloriesAvg: 780,
        image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=600&q=80',
        weeklyPrice: 1499,
        monthlyPrice: 4999,
        itemsIncluded: ['Paneer Lababdar / Kofta', 'Dal Baati with Ghee', '2 Missi Rotis & 2 Butter Phulkas', 'Kashmiri Saffron Pulao', 'Gulab Jamun / Rabdi', 'Raita & Papad'],
      },
    ],
    weeklyMenu: [
      {
        day: 'Monday',
        lunch: { curry: 'Shahi Paneer Korma', dal: 'Dal Bukhara (Slow Cooked)', bread: '2 Missi + 2 Phulkas', rice: 'Zafrani Pulao', sides: 'Dry Fruit Kheer' },
        dinner: { curry: 'Kofta Dilkhush', dal: 'Yellow Dal', bread: '4 Phulkas', rice: 'Steamed Basmati', sides: 'Anar Raita' },
      },
      {
        day: 'Tuesday',
        lunch: { curry: 'Mughlai Paneer', dal: 'Dal Tadka Ghee', bread: '4 Phulkas', rice: 'Matar Pulao', sides: 'Moong Dal Halwa' },
        dinner: { curry: 'Methi Malai Matar', dal: 'Arhar Dal', bread: '4 Phulkas', rice: 'Rice', sides: 'Salad' },
      },
      {
        day: 'Wednesday',
        lunch: { curry: 'Govind Gatta Curry', dal: 'Panchmel Dal', bread: '2 Paratha + 2 Phulka', rice: 'Jeera Rice', sides: 'Malpua & Rabdi' },
        dinner: { curry: 'Dum Paneer Kali Mirch', dal: 'Yellow Dal', bread: '4 Phulkas', rice: 'Steamed Rice', sides: 'Boondi Raita' },
      },
      {
        day: 'Thursday',
        lunch: { curry: 'Kaju Paneer Masala', dal: 'Dal Makhani', bread: '4 Butter Phulkas', rice: 'Veg Biryani', sides: 'Rasgulla' },
        dinner: { curry: 'Aloo Dum Banarasi', dal: 'Moong Dal', bread: '4 Phulkas', rice: 'Rice', sides: 'Papad' },
      },
      {
        day: 'Friday',
        lunch: { curry: 'Paneer Tikka Masala Gravy', dal: 'Dal Tadka', bread: '4 Phulkas', rice: 'Pulao', sides: 'Gajar Ka Halwa' },
        dinner: { curry: 'Navratan Korma', dal: 'Toor Dal', bread: '4 Phulkas', rice: 'Rice', sides: 'Curd' },
      },
      {
        day: 'Saturday',
        lunch: { curry: 'Royal Dal Baati Churma (7-Star)', dal: 'Panchmel Dal Ghee', bread: '3 Baatis', rice: 'Rice', sides: 'Kaju Churma' },
        dinner: { curry: 'Lauki Nazakat Kofta', dal: 'Yellow Dal', bread: '4 Phulkas', rice: 'Rice', sides: 'Salad' },
      },
      {
        day: 'Sunday',
        lunch: { curry: 'Awadhi Biryani Feast with Mirchi Salan', dal: 'Dal Makhani', bread: '2 Butter Naan', rice: 'Awadhi Biryani', sides: 'Shahi Tukda' },
        dinner: { curry: 'Sev Tameta Shahi', dal: 'Kadhi', bread: '4 Phulkas', rice: 'Khichdi', sides: 'Papad' },
      },
    ],
  },
  {
    id: 'prov-4',
    name: 'Campus Dabbawala & Parcel Point',
    tagline: 'Student & PG Mess Hub with instant takeaway lockers & doorstep delivery',
    ownerName: 'Vinod & Sachin Dabba Service',
    rating: 4.7,
    starTier: '3_star',
    kitchenCategory: 'parcel_point',
    city: 'Pune / Mumbai / Kota / Indore',
    reviewCount: 512,
    fssaiNumber: '21220194000329',
    verified: true,
    status: 'active',
    cuisine: ['Maharashtrian', 'North Indian', 'Student Mess Combo'],
    dietary: ['pure-veg', 'non-veg'],
    servicePincodes: ['411057', '400076', '324005', '452010', '560103', '388120'],
    kitchenAddress: 'Hinjewadi Phase 1 & Vigyan Nagar Student Hub',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    coverImage: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1200&q=80',
    subscriberCount: 220,
    startingPriceMonthly: 2199,
    takeawayAvailable: true,
    hasDineIn: true,
    hasParcelPoint: true,
    isStudentFavorite: true,
    isOfficeFavorite: false,
    deliverySlots: {
      lunch: '11:30 AM - 1:00 PM',
      dinner: '6:30 PM - 8:30 PM',
    },
    mealCollections: [
      {
        id: 'col-4-1',
        name: 'Pocket-Friendly Student Dabba',
        tagline: 'Unlimited Chapatis, Dal Tadka, Seasonal Sabzi & Rice',
        description: 'Nutritious student mess meal served in hot stainless steel carrier or express parcel pickup.',
        dietType: 'pure-veg',
        caloriesAvg: 600,
        image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
        weeklyPrice: 599,
        monthlyPrice: 2199,
        itemsIncluded: ['4 Chapatis', 'Dal Tadka', 'Seasonal Sabzi', 'Steamed Rice', 'Pickle & Papad'],
      },
    ],
    weeklyMenu: [
      {
        day: 'Monday',
        lunch: { curry: 'Aloo Matar', dal: 'Varan (Toor Dal)', bread: '4 Chapatis', rice: 'Steamed Rice', sides: 'Papad' },
        dinner: { curry: 'Shevga (Drumstick) Masala', dal: 'Yellow Dal', bread: '4 Chapatis', rice: 'Rice', sides: 'Pickle' },
      },
      {
        day: 'Tuesday',
        lunch: { curry: 'Chole Masala', dal: 'Dal Fry', bread: '4 Chapatis', rice: 'Jeera Rice', sides: 'Salad' },
        dinner: { curry: 'Bhendi Fry', dal: 'Dal Tadka', bread: '4 Chapatis', rice: 'Rice', sides: 'Chutney' },
      },
      {
        day: 'Wednesday',
        lunch: { curry: 'Paneer Masala', dal: 'Moong Dal', bread: '4 Chapatis', rice: 'Rice', sides: 'Gulab Jamun' },
        dinner: { curry: 'Pithla Bhakri', dal: 'Kadhi', bread: '2 Jowar Bhakri', rice: 'Khichdi', sides: 'Thecha' },
      },
      {
        day: 'Thursday',
        lunch: { curry: 'Soyabean Curry', dal: 'Dal Tadka', bread: '4 Chapatis', rice: 'Rice', sides: 'Papad' },
        dinner: { curry: 'Aloo Gobi', dal: 'Yellow Dal', bread: '4 Chapatis', rice: 'Rice', sides: 'Pickle' },
      },
      {
        day: 'Friday',
        lunch: { curry: 'Rajma Masala', dal: 'Dal Fry', bread: '4 Chapatis', rice: 'Basmati Rice', sides: 'Salad' },
        dinner: { curry: 'Egg Curry / Paneer Bhurji', dal: 'Dal', bread: '4 Chapatis', rice: 'Rice', sides: 'Papad' },
      },
      {
        day: 'Saturday',
        lunch: { curry: 'Special Pav Bhaji / Misal', dal: 'Dal', bread: '4 Pav / Chapatis', rice: 'Rice', sides: 'Sweet' },
        dinner: { curry: 'Mix Veg', dal: 'Dal Tadka', bread: '4 Chapatis', rice: 'Khichdi', sides: 'Chutney' },
      },
      {
        day: 'Sunday',
        lunch: { curry: 'Chicken Curry / Shahi Paneer Feast', dal: 'Dal Tadka', bread: '4 Chapatis', rice: 'Dum Biryani', sides: 'Raita' },
        dinner: { curry: 'Khichdi Kadhi', dal: 'Kadhi', bread: '3 Chapatis', rice: 'Khichdi', sides: 'Papad' },
      },
    ],
  },
  {
    id: 'prov-5',
    name: 'Kilimanjaro Afro-Veg Kitchen (Pan-African Homestyle)',
    tagline: 'Authentic African vegetarian & vegan stews, teff injera, jollof rice & plantains',
    ownerName: 'Chef Amina & Kemi Mensah',
    rating: 4.95,
    starTier: '7_star',
    kitchenCategory: 'cloud_kitchen',
    city: 'Bengaluru / Mumbai / Delhi / Pune',
    reviewCount: 310,
    fssaiNumber: '21224098000781',
    verified: true,
    status: 'active',
    cuisine: ['African Vegetarian', 'Ethiopian', 'West African', 'Moroccan'],
    dietary: ['pure-veg'],
    servicePincodes: ['560103', '560034', '560102', '411057', '400076', '122002', '110007', '380015'],
    kitchenAddress: 'Global Flavors Hub, Koramangala 4th Block (Also Serving Hinjewadi & BKC)',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    coverImage: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1200&q=80',
    subscriberCount: 185,
    startingPriceMonthly: 3499,
    takeawayAvailable: true,
    hasDineIn: true,
    hasParcelPoint: true,
    isStudentFavorite: true,
    isOfficeFavorite: true,
    deliverySlots: {
      lunch: '12:00 PM - 1:30 PM',
      dinner: '7:30 PM - 9:00 PM',
    },
    mealCollections: [
      {
        id: 'col-5-1',
        name: 'Ethiopian Shiro & Misir Wat Injera Feast',
        tagline: 'Spiced chickpea stew, berbere red lentils & soft fermented teff injera',
        description: 'Traditional Ethiopian slow-simmered chickpea flour Shiro Wat, spicy berbere red lentil Misir Wat, braised collards (Gomen), and 3 rolls of authentic sourdough teff Injera.',
        dietType: 'pure-veg',
        caloriesAvg: 640,
        image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
        weeklyPrice: 949,
        monthlyPrice: 3499,
        itemsIncluded: ['3 Teff Injera Flatbreads', 'Shiro Wat (Chickpea Stew)', 'Misir Wat (Spiced Red Lentils)', 'Gomen (Garlic Collard Greens)', 'Ayib Vegan Cottage Cheese', 'Awaze Pepper Dip'],
      },
      {
        id: 'col-5-2',
        name: 'West African Jollof & Kelewele Platter',
        tagline: 'Smoky party jollof rice, sweet spiced fried plantains & Egusi stew',
        description: 'Authentic fire-roasted tomato and bell pepper Jollof rice served with caramelized spiced plantains (Kelewele), spinach and melon seed Egusi stew, and stewed black-eyed peas.',
        dietType: 'pure-veg',
        caloriesAvg: 690,
        image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80',
        weeklyPrice: 999,
        monthlyPrice: 3699,
        itemsIncluded: ['Smoky Firewood Jollof Rice', 'Kelewele (Spiced Sweet Plantains)', 'Egusi Seed & Spinach Stew', 'Ewa Riro (Stewed Black-Eyed Beans)', 'Tangy Tomato Shito Pepper Sauce'],
      },
      {
        id: 'col-5-3',
        name: 'Moroccan Apricot & Chickpea Tagine',
        tagline: 'Slow-braised cinnamon saffron vegetable tagine with steamed couscous',
        description: 'North African clay pot tagine packed with tender chickpeas, golden dried apricots, roasted butternut squash, zucchini, served over fluffy steamed semolina couscous.',
        dietType: 'pure-veg',
        caloriesAvg: 610,
        image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
        weeklyPrice: 949,
        monthlyPrice: 3599,
        itemsIncluded: ['Fluffy Steamed Couscous', 'Clay Pot Chickpea & Apricot Tagine', 'Braised Butternut Squash & Zucchini', 'Harissa Tahini Dip', 'Moroccan Mint Tea Sachet'],
      },
      {
        id: 'col-5-4',
        name: 'South African Veggie Bunny Chow & Sukuma Wiki',
        tagline: 'Curried sugar bean stew in hollowed loaf with East African collards',
        description: 'Durban-style hollowed artisan bread loaf packed with spicy curried sugar beans, tender potatoes, accompanied by Kenyan Sukuma Wiki sautéed greens and carrot sambal.',
        dietType: 'pure-veg',
        caloriesAvg: 680,
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
        weeklyPrice: 899,
        monthlyPrice: 3299,
        itemsIncluded: ['Artisan Loaf Bunny Chow', 'Durban Curried Sugar Beans', 'Kenyan Sukuma Wiki (Collard Greens)', 'Crunchy Carrot & Chili Sambal', 'Fresh Lemon Wedge'],
      },
    ],
    weeklyMenu: [
      {
        day: 'Monday',
        lunch: { curry: 'Ethiopian Shiro Wat (Chickpea)', dal: 'Misir Wat (Berbere Red Lentils)', bread: '3 Teff Injera', rice: 'Jollof Rice', sides: 'Gomen Collards' },
        dinner: { curry: 'Moroccan Chickpea Tagine', dal: 'Harira Lentil Soup', bread: 'Flatbread', rice: 'Steamed Couscous', sides: 'Spiced Olives' },
      },
      {
        day: 'Tuesday',
        lunch: { curry: 'West African Egusi Spinach Stew', dal: 'Ewa Riro (Black-Eyed Beans)', bread: 'Agege Bread', rice: 'Smoky Jollof Rice', sides: 'Fried Plantains' },
        dinner: { curry: 'East African Coconut Mbaazi', dal: 'Yellow Split Pea Stew', bread: 'Chapati (East African style)', rice: 'Ugali Maize', sides: 'Sukuma Wiki' },
      },
      {
        day: 'Wednesday',
        lunch: { curry: 'South African Durban Bean Curry', dal: 'Dhal Curry', bread: 'Artisan Bunny Chow Loaf', rice: 'Turmeric Rice', sides: 'Carrot Sambal' },
        dinner: { curry: 'Senegalese Mafe Peanut Stew (Veg)', dal: 'Lentil Stew', bread: 'Millet Flatbread', rice: 'Broken Rice (Thieb)', sides: 'Sweet Potato Greens' },
      },
      {
        day: 'Thursday',
        lunch: { curry: 'Ethiopian Tikil Gomen (Cabbage & Potato)', dal: 'Defen Misir (Brown Lentils)', bread: '3 Teff Injera', rice: 'Spiced Brown Rice', sides: 'Fosolia Green Beans' },
        dinner: { curry: 'Moroccan Vegetable Tagine', dal: 'Chickpea Stew', bread: 'Khobz Bread', rice: 'Couscous with Almonds', sides: 'Harissa Dip' },
      },
      {
        day: 'Friday',
        lunch: { curry: 'Nigerian Gbegiri (Yellow Bean Stew)', dal: 'Ewedu Jute Soup', bread: 'Pounded Yam / Roti', rice: 'Coconut Jollof Rice', sides: 'Kelewele Plantains' },
        dinner: { curry: 'Ethiopian Shiro Mitein (Spiced Chickpea)', dal: 'Misir Wat', bread: '3 Teff Injera', rice: 'Rice', sides: 'Ayib Vegan Dip' },
      },
      {
        day: 'Saturday',
        lunch: { curry: 'Pan-African Royal Safari Feast Thali', dal: 'Berbere Spiced Dal', bread: 'Injera & Chapati', rice: 'Party Jollof Rice', sides: 'Fried Plantains & Sambal' },
        dinner: { curry: 'Kenyan Mahargwe (Kidney Bean Coconut Curry)', dal: 'Lentils', bread: 'Mandazi / Chapati', rice: 'Ugali', sides: 'Kachumbari Salad' },
      },
      {
        day: 'Sunday',
        lunch: { curry: 'Chef Signature Ethiopian Shiro Special', dal: 'Misir Wat & Kik Alicha', bread: '4 Fresh Teff Injera', rice: 'Wild Rice Pilaf', sides: 'Baklava / Sweet Treat' },
        dinner: { curry: 'Moroccan Sweet Apricot Tagine', dal: 'Lentils', bread: 'Warm Pita', rice: 'Jeweled Couscous', sides: 'Mint Tea' },
      },
    ],
  },
];

export const INITIAL_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 'sub-9081',
    providerId: 'prov-1',
    providerName: 'Maa Ki Rasoi (North Indian & Shahi)',
    collectionId: 'col-1-1',
    collectionName: 'Ghar Ki Thali (Standard)',
    planDuration: 'monthly',
    mealType: 'lunch',
    fulfillmentMode: 'delivery',
    startDate: '2026-10-01',
    endDate: '2026-10-28',
    totalMeals: 26,
    deliveredMeals: 4,
    skippedMeals: 1,
    remainingMeals: 21,
    status: 'active',
    deliveryAddress: INITIAL_ADDRESSES[0],
    amountPaid: 3199,
    paymentId: 'pay_RPZ_xeVAJ5Jg2C932Q',
    deliverySlot: '12:15 PM - 1:30 PM',
    dietType: 'Pure Veg',
  },
];

export const MOCK_LIVE_ORDER: LiveOrderTracking = {
  id: 'ord-8921',
  orderNumber: 'MYCHEF-ORD-8921',
  kitchenName: 'Maa Ki Rasoi (5-Star Gourmet Kitchen)',
  kitchenAddress: 'HSR Sector 2 / Near Infocity Gate',
  dishName: 'Ghar Ki Thali • Paneer Bhurji & Desi Ghee Phulkas',
  fulfillmentMode: 'delivery',
  currentStep: 3, // Step 3: Packed & Insulated
  estimatedMinutes: 18,
  deliverySlot: '12:15 PM - 1:30 PM',
  deliveryOtp: '4892',
  riderName: 'Ramesh Kumar',
  riderPhone: '+91 98451 22390',
  riderVehicle: 'Hero Electric EV • KA-05-EV-4192',
  destinationAddress: 'Flat 402, Green Glen Layout, Bellandur (560103)',
  parcelLockerCode: 'LOCKER-BOX-A12',
};

export const INITIAL_INQUIRIES: InquirySubmission[] = [
  {
    id: 'INQ-CR-901',
    category: 'corporate',
    fullName: 'Ananya Deshmukh',
    email: 'ananya.d@fintechinnovations.com',
    phone: '+91 98201 44552',
    city: 'Gandhinagar',
    pincode: '382009',
    organizationName: 'Fintech Innovations India Pvt Ltd (GIFT City)',
    estimatedMealsCount: '45-60 meals/day',
    dietaryPreference: 'all',
    startDate: '2026-10-15',
    subject: 'Corporate Lunch Subscriptions for Engineering Wing',
    message: 'We are seeking daily hygienic, low-oil lunch boxes for our tech teams at GIFT City Tower 2. We require eco-friendly packaging and monthly consolidated billing with GST.',
    status: 'new',
    createdAt: '2026-10-04T10:30:00Z',
  },
  {
    id: 'INQ-PG-842',
    category: 'student_mess',
    fullName: 'Prof. Jayesh Trivedi',
    email: 'warden@shreeshaktipg.edu',
    phone: '+91 94280 11928',
    city: 'Ahmedabad',
    pincode: '380009',
    organizationName: 'Shree Shakti Student Hostels & PG (Navrangpura)',
    estimatedMealsCount: '80-120 meals/day',
    dietaryPreference: 'pure_veg',
    startDate: '2026-10-20',
    subject: 'Hostel Mess Partner Tie-up for 100+ Students',
    message: 'We manage 3 student hostels near Gujarat University. We want to replace our old mess with MyChef quality-inspected student passes with rotational menus and QR verification.',
    status: 'contacted',
    createdAt: '2026-10-03T16:15:00Z',
  },
  {
    id: 'INQ-CF-519',
    category: 'chef_partner',
    fullName: 'Geeta Ben Sharma',
    email: 'geetaskitchen.ahd@gmail.com',
    phone: '+91 97250 88319',
    city: 'Ahmedabad',
    pincode: '380015',
    organizationName: 'Geeta Rasoi Ghar (Home Cloud Kitchen)',
    estimatedMealsCount: '25-40 tiffins/batch',
    dietaryPreference: 'pure_veg',
    startDate: '2026-10-10',
    subject: 'Partnering as Home Chef for Kathiyawadi & Gujarati Tiffins',
    message: 'I have been cooking traditional Kathiyawadi food for 15 years with an active FSSAI registration. I want to partner with MyChef for afternoon lunchbox pickups.',
    status: 'in_review',
    createdAt: '2026-10-02T11:45:00Z',
  },
  {
    id: 'INQ-EV-312',
    category: 'event_catering',
    fullName: 'Kunal Singhania',
    email: 'kunal.singhania@gmail.com',
    phone: '+91 99099 23114',
    city: 'Pune',
    pincode: '411057',
    organizationName: 'Family Diwali Gathering & Get-Together',
    estimatedMealsCount: '35 guests',
    dietaryPreference: 'custom',
    startDate: '2026-10-28',
    subject: 'Diwali Festive Traditional Feast Catering',
    message: 'Looking for a wholesome traditional feast with special sweets (Mohanthal/Shrikhand) and hot rotis for a family function at Hinjawadi, Pune.',
    status: 'resolved',
    createdAt: '2026-09-30T09:20:00Z',
  },
];
